source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorPickerView_Example', :exclusive => true do
  pod 'ColorPickerView', :path => '../'
end

target 'ColorPickerView_Tests', :exclusive => true do
  pod 'ColorPickerView', :path => '../'

  
end
